package family.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-13T20:47:25.148+02:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "FamilyDataImplService",
                  wsdlLocation = "file:/C:/Users/Dell/Desktop/inteca/i/com.inteca/src/main/resources/familydataimpl.wsdl",
                  targetNamespace = "http://service.family/")
public class FamilyDataImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.family/", "FamilyDataImplService");
    public final static QName FamilyDataImplPort = new QName("http://service.family/", "FamilyDataImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Dell/Desktop/inteca/i/com.inteca/src/main/resources/familydataimpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FamilyDataImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Dell/Desktop/inteca/i/com.inteca/src/main/resources/familydataimpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FamilyDataImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FamilyDataImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FamilyDataImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FamilyDataImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FamilyDataImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FamilyDataImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns FamilyData
     */
    @WebEndpoint(name = "FamilyDataImplPort")
    public FamilyData getFamilyDataImplPort() {
        return super.getPort(FamilyDataImplPort, FamilyData.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FamilyData
     */
    @WebEndpoint(name = "FamilyDataImplPort")
    public FamilyData getFamilyDataImplPort(WebServiceFeature... features) {
        return super.getPort(FamilyDataImplPort, FamilyData.class, features);
    }

}
